### PR TITLE
Heroku 18 w/OTP 21.3.3

### PR DESCRIPTION
**Pull request by anulman**

### CODE REVIEW

**Comment by ericmj** [comment]
Do the OTP builds fail on heroku-18 and have you confirmed that builds on heroku-18 work on cedar-14?

**Comment by anulman** [comment]
OTP 21.3.3 builds successfully on heroku-18, both in local Docker and live Heroku. I did not test earlier versions, nor heroku-18 builds running on cedar-14 stack.

Would you like me to rebase a88c0f8 before ff00814, or otherwise split the Travis change into a separate PR?

If you're peeking here, may make sense to also look at https://github.com/HashNuke/heroku-buildpack-elixir/pull/146 . I am already using these two PRs on a live heroku-18 stack running two buildpacks (rust + elixir), with an OTP build hosted elsewhere.

**Comment by HashNuke** [comment]
@anulman 
* What is the state of affairs in general? Would we have to support CEDAR-14 and the HEROKU-18 stack OR just move to the HEROKU-18 stack from the next erlang release?
* I see there is an OTP-22 coming (there are RC versions on the GitHub releases page). We can move to HEROKU-18 from OTP-22 for all builds and retain CEDAR-14 builds/support for older OTP versions. Would that be reasonable?

**Comment by anulman** [comment]
@HashNuke Pasted my suggestions on https://github.com/HashNuke/heroku-buildpack-elixir/issues/150#issuecomment-487401199; see "most resilient" for my suggestion

**Pull request closed without merging**
