### PR TITLE
Update otp-versions

### PR DESCRIPTION
**Pull request by DianaOlympos**

### CODE REVIEW

**Comment by ericmj** [comment]
This doesn't work unfortunately. We need to merge one version at a time.

**Comment by DianaOlympos** [comment]
That will be fun. One PR per version or one commit per version ? i can do it this afternoon.

**Comment by ericmj** [comment]
Separate PRs. Thank you, please check the other open PRs and open PRs for the missing versions.

**Comment by DianaOlympos** [comment]
Sure no problem

**Pull request closed without merging**
