### PR TITLE
Add 22.2.3

### PR DESCRIPTION
**Pull request by gvl**

### CODE REVIEW

**Comment by jesseshieh** [comment]
Do you need both this and 22.2.2? The build script only builds first version in the file so we'll have to merge one, rebase the other and merge it later. Or we can just pick one.

**Comment by jesseshieh** [comment]
I went ahead and merged the other one for 22.2.2. Feel free to rebase this one and we can merge it also.

**Comment by gvl** [comment]
Yes, I think we should have both versions available 👍

**Comment by jesseshieh** [comment]
Oh nm, I see you already did! Great, let's wait a bit for 22.2.2 to build and then merge this.

**Pull request merged**
