### PR TITLE
Add 22.3.4.15 to otp-versions

### PR DESCRIPTION
**Pull request by szymon-jez**
Refs https://github.com/erlang/otp/releases/tag/OTP-22.3.4.15

### CODE REVIEW

**Comment by jesseshieh** [comment]
merge conflict due to the last PR that I merged

**Comment by szymon-jez** [comment]
@jesseshieh I have merged `master` in to this PR: the `21` version was moved down in the file to the right place.

**Comment by jesseshieh** [comment]
Thanks @szymon-jez

**Comment by jesseshieh** [comment]
btw, I'm not sure if you're interested, but we might be able to avoid doing this sort of thing altogether by using the Hex OTP builds instead. While implementing support for heroku-20, I decided to use the Hex OTP builds instead. See https://github.com/HashNuke/heroku-buildpack-elixir/pull/191/files#diff-cbc5d6588d4c7ba23aca6c33fb357f15cbcfcc17133854357618389e46f247d8R5

If we switched the non-heroku-20 builds to use these, then I think it'll simplify our work here a lot. Would you be interested at all in working on that?

Adding @yellow5 also in case you're interested.

**Comment by szymon-jez** [comment]
@jesseshieh I have recently switched one of my apps to use  https://github.com/elixir-buildpack/heroku-buildpack and `heroku-20`. cc @KazW

Happy to see that `HashNuke/heroku-buildpack-elixir-otp-builds` now also has `heroku-20` support. And using Hex OTP builds is very good.

I have more apps on `heroku-16` which need upgrading to at least `heroku-18`. So I can help in testing things out.

**Pull request merged**
